name: Pre Check Plugin

on:
  pull_request:
    types: [opened, synchronize, ready_for_review, review_requested, edited]
    branches: 
      - main
      - dev
    paths-ignore:
      - "migrations/**"
      - ".scripts/**"
      - ".github/**"
      - ".gitignore"
      - "README.md"
      - "LICENSE"

env:
  REPO_NAME: khulnasoft/aiexec
  MARKETPLACE_BASE_URL: https://marketplace.aiexec.ai
  MARKETPLACE_TOKEN: placeholder
  GH_TOKEN: ${{ github.token }}

jobs:
  pre-check-plugin:
    runs-on: ubuntu-latest
    defaults:
      directory: plugins
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone Marketplace Toolkit
        run: |
          gh repo clone khulnasoft/aiexec-marketplace-toolkit -- .scripts/
      
      - name: Download Plugin Daemon
        run: |
          gh release download -R khulnasoft/aiexec --pattern "aiexec-plugin-linux-amd64" --dir .scripts
          chmod +x .scripts/aiexec-plugin-linux-amd64

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.7
      
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: yq - portable yaml processor
        uses: mikefarah/yq@v4.44.5

      - name: Get PR Path
        run: |
          export PR_FILES=$(gh pr view -R ${{ env.REPO_NAME }} ${{ github.event.pull_request.number }} --json files --jq .files)

          if PLUGIN_PATH=$(python3 .scripts/validator/check-prefix.py); then
              echo $PLUGIN_PATH
              echo "PLUGIN_PATH=$PLUGIN_PATH" >> $GITHUB_ENV
          else
            echo "PR files cross different plugin directories, skip upload."
            exit 1
          fi

      - name: Check Plugin Manifest
        run: |
          # manifest.yaml author must be khulnasoft
          if ! yq '.author' ${{ env.PLUGIN_PATH }}/manifest.yaml | grep -q "khulnasoft"; then
            echo "!!! Plugin manifest.yaml author must be khulnasoft"
            exit 1
          fi

      - name: Check If Version Exists
        run: |
          # get version, author, name
          VERSION=$(yq '.version' ${{ env.PLUGIN_PATH }}/manifest.yaml)
          AUTHOR=$(yq '.author' ${{ env.PLUGIN_PATH }}/manifest.yaml)
          NAME=$(yq '.name' ${{ env.PLUGIN_PATH }}/manifest.yaml)
          echo "Checking plugin version: $VERSION"

          # Check if the version already exists
          RESPONSE_CODE=$(curl -s -o /dev/null -w "%{http_code}" "${{ env.MARKETPLACE_BASE_URL }}/api/v1/plugins/$AUTHOR/$NAME/$VERSION")
          
          if [ "$RESPONSE_CODE" = "200" ]; then
            RESPONSE=$(curl -s "${{ env.MARKETPLACE_BASE_URL }}/api/v1/plugins/$AUTHOR/$NAME/$VERSION")
            if [ "$(echo "$RESPONSE" | jq -r '.code')" = "0" ]; then
              echo "!!! Plugin version $VERSION already exists, please update the version number in manifest.yaml"
              exit 1
            fi
          fi

      - name: Check Plugin Deps
        run: |
          if [ -f ${{ env.PLUGIN_PATH }}/requirements.txt ]; then
            echo "Trying to install plugin dependencies..."
            python3 -m venv .venv
            source .venv/bin/activate
            python3 -m pip install -r ${{ env.PLUGIN_PATH }}/requirements.txt
            deactivate
          fi

      - name: Check Plugin Install
        run: |
          if [ -f ${{ env.PLUGIN_PATH }}/requirements.txt ]; then
              source .venv/bin/activate
              pip install packaging
              aiexec_version=$(pip list | grep 'aiexec_plugin' | awk '{print $2}')
              target_version="0.0.1b64"
              result=$(python -c "from packaging.version import Version; print(0 if Version('$aiexec_version') > Version('$target_version') else 1)")
              if [ $result == 0 ]; then
                  export INSTALL_METHOD=serverless
                  export SERVERLESS_PORT=8080
                  export SERVERLESS_HOST=0.0.0.0
              else
                  export INSTALL_METHOD=aws_lambda
                  export AWS_LAMBDA_PORT=8080
                  export AWS_LAMBDA_HOST=0.0.0.0
              fi
              cd plugins/marketplace
              python3 validator/test-plugin-install.py -d ${{ env.PLUGIN_PATH }}
          fi

      - name: Check Packaging
        run: |
          cd plugins/marketplace
          python3 uploader/upload-package.py -d ${{ env.PLUGIN_PATH }} -t ${{ env.MARKETPLACE_TOKEN }} --plugin-daemon-path .scripts/aiexec-plugin-linux-amd64 -u ${{ env.MARKETPLACE_BASE_URL }} -f --test
